name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  bnt:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ["gordb", "scout"]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"

      - name: Build
        run: cd ${{ matrix.directory }} && go build -v ./...

      - name: Test Go directory
        run: cd ${{ matrix.directory }} && go test -v ./...
